#!/bin/bash
#
# Deploy contracts to local Anvil and output addresses
# Usage: ./script/deploy-local.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_ROOT/deployments"

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

echo "=== Deploying contracts to local Anvil ==="
echo ""

# Run the deployment
cd "$PROJECT_ROOT"
forge script script/DeployAnvil.s.sol --rpc-url http://localhost:8545 --broadcast 2>&1 | tee /tmp/deploy-output.txt

# Extract addresses from the broadcast file
BROADCAST_FILE="$PROJECT_ROOT/broadcast/DeployAnvil.s.sol/31337/run-latest.json"

if [ ! -f "$BROADCAST_FILE" ]; then
  echo "Error: Broadcast file not found at $BROADCAST_FILE"
  exit 1
fi

echo ""
echo "=== Extracting contract addresses ==="
echo ""

# Parse the broadcast JSON and extract deployed contract addresses
# The transactions array contains the deployed contracts in order

# Write to .env format
ENV_FILE="$OUTPUT_DIR/anvil.env"
cat > "$ENV_FILE" << 'EOF'
# Anvil Local Contract Addresses
# Generated by deploy-local.sh
# Copy these to your .env.local or environment variables

EOF

# Extract addresses using jq from broadcast file
# Note: Addresses are deterministic when deploying to a fresh Anvil instance
# We extract from the deployment output instead

# Parse the log output for addresses
grep -E "^  +[A-Z_].*:" /tmp/deploy-output.txt | while read line; do
  # Convert to env format
  key=$(echo "$line" | sed -E 's/^[[:space:]]+([^:]+):.*$/\1/' | tr '[:lower:]' '[:upper:]' | tr ' ' '_')
  value=$(echo "$line" | sed -E 's/^.*:[[:space:]]*(0x[a-fA-F0-9]+).*$/\1/')

  if [[ "$value" =~ ^0x[a-fA-F0-9]{40}$ ]]; then
    echo "VITE_${key}_ADDRESS=$value" >> "$ENV_FILE"
  fi
done

# Also create a structured output from the deployment script's known output
cat > "$OUTPUT_DIR/anvil-addresses.env" << 'EOF'
# Anvil Local Contract Addresses
# Generated by deploy-local.sh
# Copy these to your .env.local or environment variables

# Core Contracts
VITE_VSC_TOKEN_ADDRESS=0x5FbDB2315678afecb367f032d93F642f64180aa3
VITE_GEAR_STAKING_ADDRESS=0x3Aa5ebB10DC797CAC828524e59A333d0A371443c
VITE_MAINTENANCE_POOL_ADDRESS=0xc6e7DF5E7b4f2A278906862b61205850344D4e7d
VITE_REWARD_DISTRIBUTOR_ADDRESS=0x59b670e9fA9D0A427751Af201D676719a970857b

# Gear Token Addresses
VITE_WEAPON_TOKEN_ADDRESS=0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
VITE_ARMOR_TOKEN_ADDRESS=0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0
VITE_POWER_TOKEN_ADDRESS=0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
VITE_GLOVES_TOKEN_ADDRESS=0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9
VITE_AMULET_TOKEN_ADDRESS=0x5FC8d32690cc91D4c39d9d3abcBD16989F875707
VITE_BOOTS_TOKEN_ADDRESS=0x0165878A594ca255338adfa4d48449f69242Eb8F

# Bonding Curve Addresses
VITE_WEAPON_CURVE_ADDRESS=0xa513E6E4b8f2a923D98304ec87F64353C4D5C853
VITE_ARMOR_CURVE_ADDRESS=0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6
VITE_POWER_CURVE_ADDRESS=0x8A791620dd6260079BF849Dc5567aDC3F2FdC318
VITE_GLOVES_CURVE_ADDRESS=0x610178dA211FEF7D417bC0e6FeD39F05609AD788
VITE_AMULET_CURVE_ADDRESS=0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e
VITE_BOOTS_CURVE_ADDRESS=0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0
EOF

# Create JSON format for programmatic access
cat > "$OUTPUT_DIR/anvil-addresses.json" << 'EOF'
{
  "network": "anvil",
  "chainId": 31337,
  "deployedAt": "2026-02-02",
  "contracts": {
    "vscToken": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "gearStaking": "0x3Aa5ebB10DC797CAC828524e59A333d0A371443c",
    "maintenancePool": "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d",
    "rewardDistributor": "0x59b670e9fA9D0A427751Af201D676719a970857b",
    "gearTokens": {
      "weapon": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      "armor": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      "power": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      "gloves": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      "amulet": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
      "boots": "0x0165878A594ca255338adfa4d48449f69242Eb8F"
    },
    "bondingCurves": {
      "weapon": "0xa513E6E4b8f2a923D98304ec87F64353C4D5C853",
      "armor": "0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6",
      "power": "0x8A791620dd6260079BF849Dc5567aDC3F2FdC318",
      "gloves": "0x610178dA211FEF7D417bC0e6FeD39F05609AD788",
      "amulet": "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
      "boots": "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0"
    }
  }
}
EOF

echo ""
echo "=== Deployment Complete ==="
echo ""
echo "Contract addresses written to:"
echo "  - $OUTPUT_DIR/anvil-addresses.env (for .env.local)"
echo "  - $OUTPUT_DIR/anvil-addresses.json (for programmatic access)"
echo ""
echo "To use in your frontend, copy anvil-addresses.env to apps/web/.env.local"
